spring.application.name=Job_Portal

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

USER_FOUND=Email already registered
USER_NOT_FOUND= Email is not Registered
INVALID_CREDENTIALS= Invalid Credentials
JOB_NOT_FOUND=Job not Found
JOB_APPLIED_ALREADY=Already applied to selected job
JOB_HAS_APPLICANTS=Cannot delete job with existing applicants
EXPERIENCE_NOT_FOUND=Experience entry not found
CERTIFICATION_NOT_FOUND=Certification entry not found
JOB_ALREADY_SAVED=Job is already saved
JOB_NOT_SAVED=Job is not saved
UNAUTHORIZED_ACTION=You are not authorized to perform this action
