spring.application.name=Job_Portal
spring.datasource.url=jdbc:postgresql://localhost:5432/placement_portal
spring.datasource.username=postgres
spring.datasource.password=qwerty
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect




USER_FOUND=Email already registered
USER_NOT_FOUND= Email is not Registered
INVALID_CREDENTIALS= Invalid Credentials